### ISSUE TITLE
I am using vc-measure-area component  some times it is crashing

### ISSUE THREAD

**Issue by sachinsbgithub** [zouyaoji/vue-cesium#366]
### Discussed in https://github.com/zouyaoji/vue-cesium/discussions/365

<div type='discussions-op-text'>

<sup>Originally posted by **sachinsbgithub** March 14, 2023</sup>
I am using vc-measure-area component  some times it is crashing (showing  0sqm
![Screenshot 2023-03-14 104437](https://user-images.githubusercontent.com/114548996/224906455-51bf3432-b7c2-4a51-b21d-8b3b4518a31d.jpeg)
![Screenshot 2023-03-14 104512](https://user-images.githubusercontent.com/114548996/224906461-5b9398bf-7d55-439b-9561-fe0c5e0267ac.jpeg)
</div>

**Comment by zouyaoji** [comment]
hi @sachinsbgithub，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!

**Comment by sachinsbgithub** [comment]
how can i solve this issue  tell me atleast
