### ISSUE TITLE
这种方案在本地调试可以， 线上发布的时候，依赖包怎么改？

### ISSUE THREAD

**Issue by HU-Wenxing-ZuiShuai** [zouyaoji/vue-cesium#465]
这种方案在本地调试可以， 线上发布的时候，依赖包怎么改？

_Originally posted by @kankantian in https://github.com/zouyaoji/vue-cesium/discussions/382#discussioncomment-7505574_

**Comment by zouyaoji** [comment]
hi @HU-Wenxing-ZuiShuai，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
