### ISSUE TITLE
ts报错

### ISSUE THREAD

**Issue by MickeyMouse623** [zouyaoji/vue-cesium#535]
## 环境：
- "vue": "^3.4.21",
- "cesium": "^1.115.0"
- @vue/cli 5.0.6
- vscode插件使用的是`Vue - Official v2.0.7`

## 代码结构和tsconfig.json
<img width="876" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/18524460/67076583-e843-4017-b4a6-9579415e78f2">

## 异常代码
<img width="1029" alt="image" src="https://github.com/zouyaoji/vue-cesium/assets/18524460/cf9034ad-3953-4b78-9555-15da77bd01a9">

**Comment by zouyaoji** [comment]
hi @MickeyMouse623，非常感谢您的反馈，
但是由于您没有使用 [创建 issue](https://zouyaoji.top/issue-generator/#/zh-CN) 页面提交， 将直接被关闭， 谢谢！
Thank you very much for your feedback,
But since you did not submit it using the [create issue](https://zouyaoji.top/issue-generator/#/en-US) page, it will be closed directly, thank you!
